export const mockData = {
  workspaces: [
    {
      id: "workspace-001",
      name: "frontend-lab",
      description: "Workspace for UI prompt experiments",
      members: [{ email: "dev@example.com", role: "owner" }],
      owner: "12312",
      createdBy: "dunglh8",
      createdAt: new Date().toISOString(),
      updatedBy: "dunglh8",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "workspace-002",
      name: "growth-team",
      description: "Marketing and growth prompt workspace",
      members: [
        { email: "dev@example.com", role: "owner" },
        { email: "pm@example.com", role: "manager" },
        { email: "design@example.com", role: "member" },
      ],
    },
  ],
  prompts: [
    {
      id: "prompt-001",
      name: "Landing Hero Copy",
      workspace: "workspace-001",
      description: "Generate hero section copy",
      owner: "12312",
      createdBy: "dunglh8",
      createdAt: new Date().toISOString(),
      updatedBy: "dunglh8",
      updatedAt: new Date().toISOString(),
      status: "publish",
      publishedVersionId: null,
      publishedAt: null,
      publishedBy: null,
      content:
        "Write a hero headline in ${Language|options:English,Japan} for ${Product Name|text}. Tone: ${Tone|options:Bold,Friendly,Professional}",
    },
    {
      id: "prompt-002",
      name: "Landing Hero Copy 2",
      workspace: "workspace-001",
      description: "Generate hero section copy",
      owner: "12312",
      createdBy: "dunglh8",
      createdAt: new Date().toISOString(),
      updatedBy: "dunglh8",
      updatedAt: new Date().toISOString(),
      status: "publish",
      publishedVersionId: null,
      publishedAt: null,
      publishedBy: null,
      content:
        "Write a hero headline in ${Language|options:English,Japan} for ${Product Name|text}. Tone: ${Tone|options:Bold,Friendly,Professional}",
    },
    {
      id: "prompt-003",
      name: "Landing Hero Copy 3",
      workspace: "workspace-001",
      description: "Generate hero section copy",
      owner: "12312",
      createdBy: "dunglh8",
      createdAt: new Date().toISOString(),
      updatedBy: "dunglh8",
      updatedAt: new Date().toISOString(),
      status: "publish",
      publishedVersionId: null,
      publishedAt: null,
      publishedBy: null,
      content:
        "Write a hero headline in ${Language|options:English,Japan} for ${Product Name|text}. Tone: ${Tone|options:Bold,Friendly,Professional}",
    },
    {
      id: "prompt-004",
      name: "Landing Hero Copy 4",
      workspace: "workspace-001",
      description: "Generate hero section copy",
      owner: "12312",
      createdBy: "dunglh8",
      createdAt: new Date().toISOString(),
      updatedBy: "dunglh8",
      updatedAt: new Date().toISOString(),
      status: "publish",
      publishedVersionId: null,
      publishedAt: null,
      publishedBy: null,
      content:
        "Write a hero headline in ${Language|options:English,Japan} for ${Product Name|text}. Tone: ${Tone|options:Bold,Friendly,Professional}",
    },
    {
      id: "prompt-005",
      name: "Design Critic",
      workspace: "workspace-001",
      description: "Review a design JSON and suggest improvements",
      owner: "12312",
      createdBy: "dunglh8",
      createdAt: new Date().toISOString(),
      updatedBy: "dunglh8",
      updatedAt: new Date().toISOString(),
      status: "publish",
      publishedVersionId: null,
      publishedAt: null,
      publishedBy: null,
      content: "Analyze this design payload: ${Design JSON|textarea}. Reply in ${Language|options:English,Japan}",
    },
  ],
  documents: [
    {
      id: "doc-001",
      name: "growth-sheet-doc",
      type: "Spreadsheets",
      workspace: "workspace-001",
      fileName: "growth-kpis",
      preasheetId: "mock-sheet-id-001",
      description: "Weekly marketing KPI extract",
      contentMarkdown: "# growth-kpis\n\n## Overview\n\n| Metric | Value |\n| --- | --- |\n| CTR | 3.2% |",
      contentJSON: {
        name: "growth-kpis",
        sheets: [
          {
            name: "Overview",
            data: [{ Metric: "CTR", Value: "3.2%" }],
          },
        ],
      },
      contentHTML: "",
      syncOptions: {
        includeEmptyRows: false,
        headerRow: 1,
        sheets: [],
      },
      status: "publish",
      publishedVersionId: null,
      publishedAt: null,
      publishedBy: null,
    },
  ],
};
